[project]
name = "shellpoker"
version = "0.1.0"
description = "single player poker in your shell"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "rich",
    "typer",
    "toml"
]
[project.scripts]
shellpoker = "shellpoker.main:main"
